version: '3.8'
services:
  paywall-bot:
    image: yourusername/rocketchat-paywall-bot:latest
    container_name: paywall-bot
    environment:
      - ROCKETCHAT_URL=your-rocketchat-server.com
      - ROCKETCHAT_USER=paywall-bot
      - ROCKETCHAT_USE_SSL=true
      - ROCKETCHAT_ROOMS=politics,news
    secrets:
      - rocketchat_password
    restart: unless-stopped
    volumes:
      - ./paywall-sites.js:/usr/src/app/paywall-sites.js
    command: /bin/sh -c "export ROCKETCHAT_PASSWORD=$$(cat /run/secrets/rocketchat_password) && node paywallbot.js"

secrets:
  rocketchat_password:
    file: ./rocketchat_password.secret 