services:
  paywall-bot:
    image: zenjabba/rocketchat-paywall-bot:latest
    container_name: paywall-bot
    environment:
      - ROCKETCHAT_URL=https://rocketchat.zenteprise.org
      - ROCKETCHAT_USER=paywall-bot
      - ROCKETCHAT_USE_SSL=true
      - ROCKETCHAT_ROOMS=chatgpt,politics
    secrets:
      - rocketchat_password
    restart: unless-stopped
    volumes:
      - paywall-data:/usr/src/app/data
    command: /bin/sh -c "export ROCKETCHAT_PASSWORD=$$(cat /run/secrets/rocketchat_password) && node paywallbot.js"

secrets:
  rocketchat_password:
    file: ./rocketchat_password.secret

volumes:
  paywall-data: